language: python
python:
  - "3.6"
install:
  - pip install coverage python-coveralls codacy-coverage
  - pip install .
script:
  - LD_LIBRARY_PATH=/usr/lib/nvidia-396 coverage run --include="ftodtf/*" -m pytest
after_success:
  - coveralls
  - coverage xml
  - python-codacy-coverage -r coverage.xml