language: python
python:
  - "3.6"
stages:
  - test
  - docs
  - docker
jobs:
  include:
    - stage: test
      install:
        - pip install coverage codacy-coverage
        - pip install .
      script:
        - coverage run --include="ftodtf/*" -m pytest
      after_success:
        - coverage xml
        - python-codacy-coverage -r coverage.xml
    - stage: docs
      install:
        - pip install sphinx
        - pip install .
      script:
        - cd docs
        - sphinx-apidoc -o source/ ../ftodtf
        - make html
      deploy:
        provider: pages
        skip-cleanup: true
        local-dir: docs/build/html
        github-token: $GITHUB_TOKEN
        keep-history: true
        on:
          branch: master
    - stage: docker
      sudo: required
      services:
        - docker
      script:
        - docker build -t fasttext .
        - docker run --rm -it fasttext | grep "training of word-vector-embeddings"
      after_success:
        - "curl -H \"Content-Type: application/json\" --data '{\"source_type\": \"Branch\", \"source_name\": \"master\"}' -X POST https://registry.hub.docker.com/u/dbaumgarten/ftodtf/trigger/$DOCKERHUB_TOKEN/"
      on:
        branch: master
