version: '2'
services:
  worker0:
    image: dbaumgarten/ftodtf
    container_name: worker0
    command: train --job worker --workers="worker0:8888,worker1:8888" --ps="ps0:7777,ps1:7777" --log_dir /logs
    volumes:
      - ./log/distributed:/logs
      - "./:/data"
    environment:
     - PYTHONUNBUFFERED=1
  worker1:
    image: dbaumgarten/ftodtf
    container_name: worker1
    command: train --job worker --workers="worker0:8888,worker1:8888" --ps="ps0:7777,ps1:7777" --log_dir /foo --index 1 
    volumes:
      - "./:/data"
    environment:
     - PYTHONUNBUFFERED=1
  ps0:
    image: dbaumgarten/ftodtf
    container_name: ps0
    command: train --job ps --workers="worker0:8888,worker1:8888" --ps="ps0:7777,ps1:7777" --log_dir /foo
    environment:
     - PYTHONUNBUFFERED=1
  ps1:
    image: dbaumgarten/ftodtf
    container_name: ps1
    command: train --job ps --workers="worker0:8888,worker1:8888" --ps="ps0:7777,ps1:7777" --log_dir /foo --index 1
    environment:
     - PYTHONUNBUFFERED=1
  
